name: Build Debian
on:
  workflow_dispatch:
jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - name: apt
        run: sudo apt install -y devscripts equivs
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: 未知
        run: debian/rules setup
      - name: 安装依赖
        run: |
          sudo mk-build-deps -i debian/control
          rm ungoogled-chromium-build-deps_*
      - name: 编译
        run: dpkg-buildpackage -b -uc
      - name: 上传文件
        uses: actions/upload-artifact@v4
